### PR TITLE
Updated to latest version of pipeline scanner

### PR DESCRIPTION
**Pull request by stevewithey**
The current version of this extension does not support the --include flag.  This PR is to try force an upgrade to the latest version of the scanner.  Please review and test it before publishing!

### CODE REVIEW

**Comment by julz0815** [comment]
Thanks for pointing this out @stevewithey. Will review this over the weekend. Also it looked like the automation didn't run anymore as there were no code changes 🤔. That was also enabled again now.

**Comment by stevewithey** [comment]
Thanks @julz0815 note that I manually set the version number and arguments, I've not checked if there are any other new ones missing/deprecated ones, but hopefully you can verify that!

**Comment by julz0815** [comment]
@stevewithey I have updated the version a little differently and will close this PR without merging. The --include functionality is now working with the latest version of the plug-in (v0.1.18)

**Comment by stevewithey** [comment]
Amazing, thank you!

**Pull request closed without merging**
